import type { ProReviewSubmission } from '../../lib/proLabReviewIntake'

/**
 * Generated by scripts/prolab-ingest-review.mjs.
 * JSON is cast only for TypeScript import compatibility; the production
 * evidence registry re-validates every record and fails invalid evidence closed.
 */
export const proReviewedSubmissions: readonly ProReviewSubmission[] = []
